import Head from 'next/head';
import Image from 'next/image';
import Heads from '../components/Heads';
import Social from '../components/Social';
import Slide from '../components/Slide';
import { SlideData } from '../components/SlideData';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Photography-site</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Heads heading='Frame The Nature' message="From Lens to World, Share Your Earthly Wonders on EarthFrame"  para="Share" />
      <Slide slides={SlideData} />
      <Social />
    </div>
  );
}
